config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions'}
  root to: 'pages#home'

  get 'dashboard', to: 'dashboard/dashboard#index', as: :dashboard
  get 'dashboard/products', to: 'dashboard/products#index', as: :dashboard_products
  get 'dashboard/articles', to: 'dashboard/articles#index', as: :dashboard_articles
  get 'dashboard/categories', to: 'dashboard/categories#index', as: :dashboard_categories
  get 'dashboard/coffrets', to: 'dashboard/coffrets#index', as: :dashboard_coffrets
  get 'dashboard/prestations', to: 'dashboard/prestations#index', as: :dashboard_prestations
  get 'dashboard/general', to: 'dashboard/general#index', as: :dashboard_general
  get 'dashboard/gardens', to: 'dashboard/jardins#index', as: :dashboard_jardins
  get 'dashboard/orders', to: 'dashboard/orders#index', as: :dashboard_orders
  get 'dashboard/users', to: 'dashboard/users#index', as: :dashboard_users
  get 'contact', to: 'pages#contact'
  get 'cgv', to: 'pages#cgv'

  get 'carts/:id', to: "carts#show", as: 'cart'
  delete 'carts/:id', to: "carts#destroy"

  post 'line_items', to: "line_items#create"
  get 'line_items/:id', to: "line_items#show", as: "line_item"
  delete 'line_items/:id', to: "line_items#destroy"
  post 'line_items/:id/add', to: "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce', to: "line_items#reduce_quantity", as: "line_item_reduce"


  resources :about_mes, only: [:new, :create, :edit, :update, :destroy]
  resources :articles
  resources :categories, only: [:create, :edit, :update, :destroy]
  resources :coffrets, except: :show
  resources :coffret_on_demands, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :contacts, only: [:new, :create]
  resources :images, except: :show
  resources :jardins, except: :show
  resources :orders do
    resources :payments, only: :new
  end
  resources :prestation_categories, except: :new, path: 'presta'
  resources :prestations, except: :show
  resources :products
  resources :rayons, except: [:index, :new], path: 'classe'

  mount StripeEvent::Engine, at: '/stripe-webhooks'

end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items
  has_many :products, through: :line_items
  has_many :coffrets, through: :line_items
  has_many :coffret_on_demands, through: :line_items

  def sub_total
    sum = 0
    self.line_items.each do |line_item|
      sum+= line_item.total_price
    end
    return sum
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show, :destroy]

  def show
    @cart = @current_cart
  end

  def destroy
    @cart = @current_cart
    @cart.destroy
    session[:cart_id] = nil
    redirect_to root_path
  end

  private
  def cart_params
    params.require(:cart).permit(:line_item_ids)
  end
end

app/views/carts/show.html.erb
<% content_for :meta_title, "Mon panier - #{DEFAULT_META["meta_product_name"]}" %>
<div class="title">
  <h1>Votre panier</h1>
</div>
<% @cart.line_items.sort.each do |line_item| %>
  <div class="line-items">
    <% if line_item.product_id %>
      <div class="product-image">
        <% if line_item.product.main_photo.attached? %>
          <%= cl_image_tag line_item.product.main_photo.key %>
        <% else %>
          <%= image_tag "SVG/Leafs.svg" %>
        <% end %>
      </div>
      <div class="product-info">
        <h4><%= line_item.product.title %> x <%= line_item.quantity %></h4>
        <% if line_item.product.discount.nil? %>
          <span>Prix à l'unité : <%= line_item.product.price %> <%= line_item.product.price_currency %>.</span>
        <% else %>
          <span>Prix à l'unité : <strong><%= line_item.product.price_with_discount %> <%= line_item.product.price_currency %></strong>  au lieu de <%= line_item.product.price %> <%= line_item.product.price_currency %> (-<%= line_item.product.discount %>%).</span>
        <% end %>
        <br>
        <h5>Prix total : <%= (line_item.total_price) %> <%= (line_item.product.price_currency) %>.</h5>
      </div>
      <div class="cart-buttons">
        <div class="add-reduce-buttons">
          <%= link_to line_item_add_path(id: line_item), data: { turbo_method: :post }, remote: true  do %>
          <span>+</span>
          <% end %>
          <span class="quantity"><%= line_item.quantity %></span>
          <%= link_to line_item_reduce_path(id: line_item), data: { turbo_method: :post }, remote: true do %>
          <span>-</span>
          <% end %>
        </div>
        <button>
          <%= link_to "Supprimer l'article du panier", line_item_path(line_item), data: { turbo_method: :delete }, remote: true %>
        </button>
      </div>
    <% elsif line_item.coffret_id %>
      <div class="product-image">
        <% if line_item.coffret.main_photo.attached? %>
          <%= cl_image_tag line_item.coffret.main_photo.first.key %>
        <% else %>
          <%= image_tag "SVG/Leafs.svg" %>
        <% end %>
      </div>
      <div class="product-info">
        <h4><%= line_item.coffret.title %> x <%= line_item.quantity %></h4>
        <span>Prix à l'unité : <%= (line_item.coffret.price) %> <%= (line_item.coffret.price_currency) %></span>
        <br>
        <h5>Prix total : <%= (line_item.total_price) %> <%= (line_item.coffret.price_currency) %></h5>
      </div>
      <div class="cart-buttons">
        <div class="add-reduce-buttons">
          <%= link_to line_item_add_path(id: line_item), data: { turbo_method: :post }, remote: true do %>
          <span>+</span>
          <% end %>
          <span class="quantity"><%= line_item.quantity %></span>
          <%= link_to line_item_reduce_path(id: line_item), data: { turbo_method: :post }, remote: true do %>
          <span>-</span>
          <% end %>
        </div>
        <button>
          <%= link_to "Supprimer l'article du panier", line_item_path(line_item), data: { turbo_method: :delete }, remote: true %>
        </button>
      </div>
    <% elsif line_item.coffret_on_demand_id %>
      <div class="product-image">
        <%= image_tag "SVG/Leafs.svg" %>
      </div>
      <div class="product-info">
        <h4>Votre Coffret à la demande x <%= line_item.quantity %></h4>
        <span>Prix à l'unité : <%= (line_item.coffret_on_demand.price) %> <%= (line_item.coffret_on_demand.price_currency) %></span>
        <br>
        <h5>Prix total : <%= (line_item.total_price) %> <%= (line_item.coffret_on_demand.price_currency) %></h5>
      </div>
      <div class="cart-buttons">
        <div class="add-reduce-buttons">
          <%= link_to line_item_add_path(id: line_item), data: { turbo_method: :post }, remote: true do %>
          <span>+</span>
          <% end %>
          <span class="quantity"><%= line_item.quantity %></span>
          <%= link_to line_item_reduce_path(id: line_item), data: { turbo_method: :post }, remote: true do %>
          <span>-</span>
          <% end %>
        </div>
        <button>
          <%= link_to "Supprimer l'article du panier", line_item_path(line_item), data: { turbo_method: :delete }, remote: true %>
        </button>
      </div>
    <% end  %>
  </div>
<% end %>
<div class="total-price">
  <h3>Total: <%= (@cart.sub_total) %> €</h3>
  <p><em>Des frais d'envoi s'appliqueront lors du paiement.</em></p>
</div>
<div class="cart-actions">
  <button class="cart-validation">
    <%= link_to "Valider le panier", new_order_path %><br>
  </button>
  <br>
  <%= button_to "Vider le panier", cart_path(@current_cart),method: :delete, data: {confirm: "Êtes vous sûr ?"} %>
</div>