config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions'}
  root to: 'pages#home'

  get 'dashboard', to: 'dashboard/dashboard#index', as: :dashboard
  get 'dashboard/products', to: 'dashboard/products#index', as: :dashboard_products
  get 'dashboard/articles', to: 'dashboard/articles#index', as: :dashboard_articles
  get 'dashboard/categories', to: 'dashboard/categories#index', as: :dashboard_categories
  get 'dashboard/coffrets', to: 'dashboard/coffrets#index', as: :dashboard_coffrets
  get 'dashboard/prestations', to: 'dashboard/prestations#index', as: :dashboard_prestations
  get 'dashboard/general', to: 'dashboard/general#index', as: :dashboard_general
  get 'dashboard/gardens', to: 'dashboard/jardins#index', as: :dashboard_jardins
  get 'dashboard/orders', to: 'dashboard/orders#index', as: :dashboard_orders
  get 'dashboard/users', to: 'dashboard/users#index', as: :dashboard_users
  get 'contact', to: 'pages#contact'
  get 'cgv', to: 'pages#cgv'

  get 'carts/:id', to: "carts#show", as: 'cart'
  delete 'carts/:id', to: "carts#destroy"

  post 'line_items', to: "line_items#create"
  get 'line_items/:id', to: "line_items#show", as: "line_item"
  delete 'line_items/:id', to: "line_items#destroy"
  post 'line_items/:id/add', to: "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce', to: "line_items#reduce_quantity", as: "line_item_reduce"


  resources :about_mes, only: [:new, :create, :edit, :update, :destroy]
  resources :articles
  resources :categories, only: [:create, :edit, :update, :destroy]
  resources :coffrets, except: :show
  resources :coffret_on_demands, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :contacts, only: [:new, :create]
  resources :images, except: :show
  resources :jardins, except: :show
  resources :orders do
    resources :payments, only: :new
  end
  resources :prestation_categories, except: :new, path: 'presta'
  resources :prestations, except: :show
  resources :products
  resources :rayons, except: [:index, :new], path: 'classe'

  mount StripeEvent::Engine, at: '/stripe-webhooks'

end

app/models/coffret.rb
class Coffret < ApplicationRecord
  has_many :products
  belongs_to :user
  has_many :line_items, dependent: :destroy

  has_many_attached :main_photo

  serialize :coffret_products, Array

  monetize :price_cents

  validates :title, presence: true
  validates :description, presence: true
  validates :price_cents, presence: true
end

app/controllers/coffrets_controller.rb
class CoffretsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @coffrets = Coffret.all
    @products = Product.all
    @coffret_on_demand = CoffretOnDemand.new
  end

  def new
    @coffret = Coffret.new
  end

  def create
    @coffret = Coffret.new(coffret_params)
    @coffret.user = current_user
    coffret_products_params = params[:coffret][:product_ids]
    coffret_products_params.delete("")
    coffret_products = Product.find(coffret_products_params)
    @coffret.coffret_products = coffret_products
    if current_user.admin?
      @coffret.save
      redirect_to dashboard_coffrets_path
    else
      render :new
    end
  end

  def edit
    @coffret = Coffret.find(params[:id])
    @filtered_products = Product.where(sku: [false, nil])
  end

  def update
    @coffret = Coffret.find(params[:id])
    coffret_products_params = params[:coffret][:product_ids]
    coffret_products_params.delete("")
    coffret_products = Product.find(coffret_products_params)
    @coffret.coffret_products = coffret_products
    if current_user.admin?
      @coffret.update(coffret_params)
      redirect_to dashboard_coffrets_path
    else
      render :new
    end
  end

  def destroy
    @coffret = Coffret.find(params[:id])
    @coffret.destroy
    redirect_to dashboard_coffrets_path
  end

  private

  def coffret_params
    params.require(:coffret).permit(:title, :description, :price_cents, :price_currency, :coffret_products, :product_ids, main_photo: [])
  end

end

app/controllers/dashboard/coffrets_controller.rb
class Dashboard::CoffretsController < ApplicationController

  def index
    @coffret_on_demands = CoffretOnDemand.all
    @coffrets = Coffret.all
    @coffret = Coffret.new
    @filtered_products = Product.where(sku: [false, nil])
  end
end

app/helpers/dashboard/coffrets_helper.rb
module Dashboard::CoffretsHelper
end

app/views/coffrets/edit.html.erb
<% if current_user.admin? %>
<div class="dashboard">
  <%= render "shared/navbar_dashboard" %>
  <div class="dashboard-container">
    <h3>Éditer <%= @coffret.title %></h3>
    <br>
    <%= simple_form_for(@coffret) do |f| %>
        <%= f.input :title, placeholder: "Nom du coffret", label: false %>
        <%= f.input :description, placeholder: "Description du coffret", label: false %>
        <%= f.input :price_cents, label: "Prix du coffret (mettre le prix en centimes)" %>
        <%= f.input :main_photo, as: :file, input_html: { multiple: true }, placeholder: "Photos du coffret", label: "Photos du coffret" %>
        <%= f.association :products, collection: @filtered_products, label: "Selectionne plusieurs produits pour ton coffret :" %>
        <button>
          <%= f.button :submit, "Publier" %>
        </button>
    <% end %>
  </div>
</div>
<% else %>
    <p>Vous n'êtes pas autorisé à consulter cette page.</p>
<% end  %>

app/views/coffrets/index.html.erb
<% content_for :meta_title, "Mes Coffrets bio - #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, "Découvrez mes coffrets à base de plantes bio ceuillies dans mes jardins de Beuil et de Cantaron" %>
<% content_for :meta_image, cl_image_path(@coffrets.first.main_photo.first.key) if @coffrets.first.main_photo.first.present? %>
<div data-controller="switch-tab scroll active-nav">
  <div class="navbar-small">
  <%= link_to new_coffret_on_demand_path do %>
    <span>Composer votre coffret</span>
  <% end %>
  <% @coffrets.each do |coffret| %>
      <a id="<%= I18n.transliterate(coffret.title.gsub(/\s+/, "")) %>" class="" data-action="click->switch-tab#switch click->scroll#scroll" data-switch-tab-target="tab" data-active-nav-target="tab" data-tab-name="<%= coffret.title %>"><%= coffret.title %></a>
  <%end %>
  </div>
  <div class="title" data-scroll-target="title" data-active-nav-target="scroll">
    <h1>Coffrets</h1>
  </div>
  <%= render 'shared/pop_up' %>
  <%= render 'shared/coffrets_index' %>
  <% @coffrets.each do |coffret| %>
  <div id="<%= I18n.transliterate(coffret.title.gsub(/\s+/, "")) %>" class="content" data-switch-tab-target="content" data-active-nav-target="content" data-tab-name="<%= coffret.title %>">
    <div class="sticker-title">
      <h2><%= coffret.title %></h2>
    </div>
    <div class="coffret-container">
      <div class="coffret-main">
        <div class="coffret-image swiper" data-controller="carousel">
          <div class="swiper-wrapper">
            <% if coffret.main_photo.attached? %>
              <% coffret.main_photo.each do |img| %>
                <div class="swiper-slide">
                 <%= cl_image_tag img.key %>
                </div>
              <% end %>
            <% else %>
              <%= image_tag "SVG/Leafs.svg" %>
            <% end %>
          </div>
          <div class="swiper-button-prev"></div>
          <div class="swiper-button-next"></div>
        </div>
        <div class="coffret-infos">
          <p><%= coffret.description %></p>
          <div class="details">
            <h4><%= coffret.price %> <%= coffret.price_currency %></h4>
            <%= link_to line_items_path(coffret_id: coffret.id), data: { turbo_method: :post } do %>
                  <button>Ajouter au panier <%= image_tag "SVG/panier.svg" %></button>
            <% end %>
          </div>
        </div>
      </div>
      <div class="coffret-products">
        <% coffret.coffret_products.each do |product| %>
          <div class="product" data-controller="hover-images">
              <div class="product-image" data-action='mouseleave->hover-images#showImage mouseenter->hover-images#showInfos' data-hover-images-target="img">
                <% if product.main_photo.attached? %>
                  <div class="background" style="background-image: url(<%= cl_image_path product.main_photo.key %>)">
                    <h4><%= product.title %></h4>
                  </div>
                <% else %>
                  <div class="background" style="background-color: rgb(231, 231, 231)">
                    <h4><%= product.title %></h4>
                  </div>
                <% end %>
              </div>
              <div class="product-info d-none" data-action='mouseleave->hover-images#showImage mouseenter->hover-images#showInfos' data-hover-images-target="infos">
                <p><%= sanitize("#{product.description}".truncate(100)) %></p>
                <p><strong>Quantité :</strong> <%= product.quantity %></p>
                <p><strong>Origine :</strong> <%= product.origin %></p>
              </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <% end %>
</div>