config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions'}
  root to: 'pages#home'

  get 'dashboard', to: 'dashboard/dashboard#index', as: :dashboard
  get 'dashboard/products', to: 'dashboard/products#index', as: :dashboard_products
  get 'dashboard/articles', to: 'dashboard/articles#index', as: :dashboard_articles
  get 'dashboard/categories', to: 'dashboard/categories#index', as: :dashboard_categories
  get 'dashboard/coffrets', to: 'dashboard/coffrets#index', as: :dashboard_coffrets
  get 'dashboard/prestations', to: 'dashboard/prestations#index', as: :dashboard_prestations
  get 'dashboard/general', to: 'dashboard/general#index', as: :dashboard_general
  get 'dashboard/gardens', to: 'dashboard/jardins#index', as: :dashboard_jardins
  get 'dashboard/orders', to: 'dashboard/orders#index', as: :dashboard_orders
  get 'dashboard/users', to: 'dashboard/users#index', as: :dashboard_users
  get 'contact', to: 'pages#contact'
  get 'cgv', to: 'pages#cgv'

  get 'carts/:id', to: "carts#show", as: 'cart'
  delete 'carts/:id', to: "carts#destroy"

  post 'line_items', to: "line_items#create"
  get 'line_items/:id', to: "line_items#show", as: "line_item"
  delete 'line_items/:id', to: "line_items#destroy"
  post 'line_items/:id/add', to: "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce', to: "line_items#reduce_quantity", as: "line_item_reduce"


  resources :about_mes, only: [:new, :create, :edit, :update, :destroy]
  resources :articles
  resources :categories, only: [:create, :edit, :update, :destroy]
  resources :coffrets, except: :show
  resources :coffret_on_demands, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :contacts, only: [:new, :create]
  resources :images, except: :show
  resources :jardins, except: :show
  resources :orders do
    resources :payments, only: :new
  end
  resources :prestation_categories, except: :new, path: 'presta'
  resources :prestations, except: :show
  resources :products
  resources :rayons, except: [:index, :new], path: 'classe'

  mount StripeEvent::Engine, at: '/stripe-webhooks'

end

app/models/prestation.rb
class Prestation < ApplicationRecord
  belongs_to :user
  belongs_to :prestation_category

  validates :title, presence: true
  validates :description, presence: true
  validates :dates, presence: true
  has_rich_text :description

  has_one_attached :main_photo
  has_many_attached :photos_url

end

app/controllers/dashboard/articles_controller.rb
class Dashboard::ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end
end

app/controllers/dashboard/categories_controller.rb
class Dashboard::CategoriesController < ApplicationController

  def index
    @category = Category.new
    @categories = Category.all
    @rayons = Rayon.all
    @rayon = Rayon.new
  end
end

app/controllers/dashboard/coffrets_controller.rb
class Dashboard::CoffretsController < ApplicationController

  def index
    @coffret_on_demands = CoffretOnDemand.all
    @coffrets = Coffret.all
    @coffret = Coffret.new
    @filtered_products = Product.where(sku: [false, nil])
  end
end

app/controllers/dashboard/dashboard_controller.rb
class Dashboard::DashboardController < ApplicationController

  def index
  end
end

app/controllers/dashboard/general_controller.rb
class Dashboard::GeneralController < ApplicationController

  def index
    @about_me = AboutMe.new
    @about_mes = AboutMe.all
    @images = Image.all
    @image = Image.new
  end

end

app/controllers/dashboard/jardins_controller.rb
class Dashboard::JardinsController < ApplicationController

  def index
    @jardins = Jardin.all
    @jardin = Jardin.new
  end

end

app/controllers/dashboard/orders_controller.rb
class Dashboard::OrdersController < ApplicationController

  def index
    if params[:query].present?
      @orders = Order.global_search(params[:query])
    else
      @orders = Order.all.reverse
    end

    respond_to do |format|
      format.html
      format.text { render partial: 'list.html', locals: { orders: @orders } }
    end
  end

end

app/controllers/dashboard/prestations_controller.rb
class Dashboard::PrestationsController < ApplicationController

  def index
    @prestations = Prestation.all
    @prestation = Prestation.new
    @prestation_categories = PrestationCategory.all
    @prestation_category = PrestationCategory.new
  end

end

app/controllers/dashboard/products_controller.rb
class Dashboard::ProductsController < ApplicationController

  def index
     @products = Product.all.reverse
  end
end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < ApplicationController

  def index
    @users = User.all
  end

end

app/controllers/prestations_controller.rb
class PrestationsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @prestations = Prestation.all
  end

  def new
    @prestation = Prestation.new
  end

  def create
    @prestation = Prestation.new(prestation_params)
    @prestation.user = current_user
    if current_user.admin?
      @prestation.save
      redirect_to dashboard_categories_path
    else
      render :new
    end
  end

  def edit
    @prestation = Prestation.find(params[:id])
  end

  def update
    @prestation = Prestation.find(params[:id])
    if current_user.admin?
      @prestation.update(prestation_params)
      redirect_to dashboard_categories_path
    else
      render :new
    end
  end

  def destroy
    @prestation = Prestation.find(params[:id])
    @prestation.destroy
    redirect_to dashboard_categories_path
  end

  private

  def prestation_params
    params.require(:prestation).permit(:title, :description, :dates, :prestation_category_id, :main_photo, photos_url: [])
  end

end

app/helpers/dashboard/articles_helper.rb
module Dashboard::ArticlesHelper
end

app/helpers/dashboard/categories_helper.rb
module Dashboard::CategoriesHelper
end

app/helpers/dashboard/coffrets_helper.rb
module Dashboard::CoffretsHelper
end

app/helpers/dashboard/dashboard_helper.rb
module Dashboard::DashboardHelper
end

app/helpers/dashboard/general_helper.rb
module Dashboard::GeneralHelper
end

app/helpers/dashboard/jardins_helper.rb
module Dashboard::JardinsHelper
end

app/helpers/dashboard/orders_helper.rb
module Dashboard::OrdersHelper
end

app/helpers/dashboard/prestations_helper.rb
module Dashboard::PrestationsHelper
end

app/views/dashboard/prestations/index.html.erb
<div class="dashboard" data-controller="switch-tab">
  <%= render "shared/navbar_dashboard" %>
  <div class="dashboard-container">
    <div class="dashboard-title">
      <h2>Prestations</h2>
      <span><%= link_to 'Voir toutes les prestations', prestation_categories_path %></span>
    </div>
    <div class="tabs">
      <h3 class="colored" data-switch-tab-target="subTab" data-action="click->switch-tab#activate" data-tab-name="type-presta">Types de prestations</h3>
      <h3 class="" data-switch-tab-target="subTab" data-action="click->switch-tab#activate" data-tab-name="mes-presta">Mes prestations</h3>
    </div>
    <br>
    <div class="panel activate" data-switch-tab-target="panel" data-tab-name="type-presta">
      <% @prestation_categories.each do |prestation| %>
        <div class="title-btn">
          <h5 data-switch-tabs-target="title" data-action="click->switch-tab#show" data-tab-name="<%= prestation.title %>"><%= prestation.title %></h5>
          <button data-switch-tabs-target="title" data-action="click->switch-tab#show" data-tab-name="<%= prestation.title %>">↓</button>
        </div>
        <div class="small-dash-container" data-switch-tab-target="project" data-tab-name="<%= prestation.title %>">
          <div class="main-photo">
            <% if prestation.main_photo.attached? %>
              <%= cl_image_tag prestation.main_photo.key %>
            <% else %>
              <%= image_tag "SVG/Leafs.svg" %>
            <% end %>
          </div>
          <div class="infos">
            <p><%= prestation.description %></p>
          </div>
          <div class="buttons">
          <button><%= link_to 'Éditer', edit_prestation_category_path(prestation) %></button>
          <button><%= link_to "Supprimer", prestation_category_path(prestation), remote: true, data: { turbo_confirm: "Es-tu vraiment sûre de ton choix Alice ?", turbo_method: :delete } %></button>
          </div>
        </div>
        <hr>
      <% end %>
      <br>
      <h4>Créer un nouveau type de prestation</h4>
      <br>
      <%= simple_form_for(@prestation_category) do |f| %>
          <%= f.input :title, placeholder: "Nom du type de prestation", label: false %>
          <%= f.input :description, placeholder: "Description du type de prestation", label: false %>
          <%= f.input :main_photo, as: :file, placeholder: "Photo principale", label: "Photo principale :" %>
          <%= f.input :photos, as: :file, input_html: { multiple: true }, placeholder: "Galerie de photos pour le type de prestation", label: "Galerie de photos pour le type de prestation créée :" %>
          <button>
            <%= f.button :submit, "Créer le type de prestation" %>
          </button>
      <% end %>
    </div>
    <br>
    <div class="panel" data-switch-tab-target="panel" data-tab-name="mes-presta">
      <% @prestations.each do |prestation| %>
        <div class="title-btn">
          <h5 data-switch-tabs-target="title" data-action="click->switch-tab#show" data-tab-name="<%= prestation.title %>"><%= prestation.title %></h5>
          <button data-switch-tabs-target="title" data-action="click->switch-tab#show" data-tab-name="<%= prestation.title %>">↓</button>
        </div>
        <div class="small-dash-container" data-switch-tab-target="project" data-tab-name="<%= prestation.title %>">
          <div class="main-photo">
            <% if prestation.main_photo.attached? %>
              <%= cl_image_tag prestation.main_photo.key %>
            <% else %>
              <%= image_tag "SVG/Leafs.svg" %>
            <% end %>
          </div>
          <div class="infos">
            <p><%= prestation.description %></p>
            <p><strong>Type de prestation : </strong><%= prestation.prestation_category.title %></p>
            <span><strong>Dates : </strong><%= prestation.dates %></span>
          </div>
          <div class="buttons">
          <button><%= link_to 'Éditer', edit_prestation_path(prestation) %></button>
          <button><%= link_to "Supprimer", prestation_path(prestation), method: :delete, remote: true, data: { turbo_confirm: "Es-tu vraiment sûre de ton choix Alice ?", turbo_method: :delete } %></button>
          </div>
        </div>
        <hr>
      <% end %>
      <br>
      <h4>Créer une nouvelle prestation</h4>
      <br>
      <%= simple_form_for(@prestation) do |f| %>
          <%= f.input :title, placeholder: "Nom de la prestation", label: false %>
          <%= f.rich_text_area :description, placeholder: "Description de la prestation", label: false %>
          <br>
          <%= f.input :dates, placeholder: "Dates de la prestation", label: false %>
          <hr>
          <%= f.association :prestation_category, prompt: "Selectionne un type de prestation", label: false %>
          <hr>
          <button>
            <%= f.button :submit, "Mettre la prestation en ligne" %>
          </button>
      <% end %>
    </div>
  </div>
</div>